services:
  db-postgres:
    image: bitnami/postgresql
    container_name: db-postgres
    volumes: 
      - db:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
      - POSTGRESQL_PORT_NUMBER=5444
    networks:
      - aula_03_network
  
  api-solid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-solid
    ports:
      - 3333:3333
    depends_on:
      - db-postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://docker:docker@db-postgres:5444/apisolid?schema=public
      - JWT_SECRET=asdfasdfadsf
      - PORT=3333
    networks:
      - aula_03_network

networks:
  aula_03_network:
    driver: bridge

volumes:
  db: